import type { School, Student } from "@/lib/types";

/**
 * Student identity (spec §22):
 * - Student ID: generated by the platform as SCHOOL/YY/NNNN (school short name,
 *   admission year, running number) — read-only and never reused.
 * - JHS (BECE) index number: the 10 digits from the student's BECE results.
 * - Index number: the JHS index with the two-digit admission year appended —
 *   12 digits, e.g. 0012345678 admitted in 2026 → 001234567826. It is unique
 *   across the platform, so it finds a student anywhere and matches imported
 *   records to existing ones.
 */
export const JHS_INDEX_DIGITS = 10;

export const isJhsIndex = (v: string | undefined) => !!v && /^\d{10}$/.test(v);

export function indexNumberOf(jhsIndex: string, admissionYear: number | string): string {
  return `${jhsIndex}${String(admissionYear).slice(-2)}`;
}

/** Problem with an admission year, or null. Allows back to 1990 and up to next year. */
export function admissionYearProblem(year: string | number, now = new Date()): string | null {
  const s = String(year);
  if (!/^\d{4}$/.test(s)) return "Enter a four-digit year, e.g. 2026";
  const y = Number(s);
  if (y < 1990 || y > now.getFullYear() + 1) return `Enter a year between 1990 and ${now.getFullYear() + 1}`;
  return null;
}

/** Next free Student IDs for a school, one per admission year given (in order). */
export function nextStudentNumbers(school: Pick<School, "shortName">, existing: Pick<Student, "studentNumber" | "schoolId">[], years: (number | string)[]): string[] {
  const prefix = school.shortName.toUpperCase();
  const next = new Map<string, number>();
  const seqFor = (yy: string) => {
    if (!next.has(yy)) {
      const re = new RegExp(`^${prefix.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}/${yy}/(\\d+)$`, "i");
      const max = existing.reduce((m, s) => Math.max(m, Number(re.exec(s.studentNumber)?.[1] ?? 0)), 0);
      next.set(yy, max + 1);
    }
    const n = next.get(yy)!;
    next.set(yy, n + 1);
    return n;
  };
  return years.map((y) => {
    const yy = String(y).slice(-2);
    return `${prefix}/${yy}/${String(seqFor(yy)).padStart(4, "0")}`;
  });
}

/** 12-digit index numbers already registered anywhere on the platform → "Name (School)". */
export function takenIndexNumbers(students: Student[], schools: Pick<School, "id" | "shortName">[], exceptStudentId?: string): Map<string, string> {
  const m = new Map<string, string>();
  for (const s of students) if (s.indexNumber && s.id !== exceptStudentId) m.set(s.indexNumber, `${s.firstName} ${s.lastName} (${schools.find((x) => x.id === s.schoolId)?.shortName ?? "another school"})`);
  return m;
}
