import type { School, Student, Teacher, User } from "@/lib/types";

/**
 * Sign-in identities (spec §10.1).
 *
 * - Platform username: every user gets one, generated by the system, unique
 *   across the whole platform and never changed. Other products integrate
 *   against it.
 * - School username (students): the school's WAEC code as a prefix plus a
 *   sequence, e.g. 0010712-0042. Only issued once the school has a WAEC code;
 *   until then the student signs in with the platform username.
 * - Staff ID (teachers): collected from the teacher (Teacher.staffNumber).
 */

export const PLATFORM_USERNAME_PREFIX = "cp";
const PLATFORM_BASE = 1_000_000;

export const isValidWaec = (code: string | undefined) => /^\d{7}$/.test(code ?? "");

/** Next free platform usernames, continuing from the highest one issued. */
export function nextPlatformUsernames(users: Pick<User, "username">[], count: number): string[] {
  let max = PLATFORM_BASE;
  for (const u of users) {
    const n = Number(u.username?.slice(PLATFORM_USERNAME_PREFIX.length));
    if (u.username?.startsWith(PLATFORM_USERNAME_PREFIX) && Number.isFinite(n) && n > max) max = n;
  }
  return Array.from({ length: count }, (_, i) => `${PLATFORM_USERNAME_PREFIX}${max + i + 1}`);
}

export const schoolUsername = (waec: string, seq: number) => `${waec}-${String(seq).padStart(4, "0")}`;

/** Highest sequence already issued under this WAEC prefix. */
function maxSeq(students: Pick<Student, "schoolUsername">[], waec: string) {
  let max = 0;
  for (const s of students) {
    if (!s.schoolUsername?.startsWith(`${waec}-`)) continue;
    const n = Number(s.schoolUsername.slice(waec.length + 1));
    if (Number.isFinite(n) && n > max) max = n;
  }
  return max;
}

/** A student needs a (new) school username when it's missing or uses an old WAEC prefix. */
export const needsSchoolUsername = (st: Pick<Student, "schoolUsername">, school: Pick<School, "waecCode"> | undefined) =>
  !!school && isValidWaec(school.waecCode) && !st.schoolUsername?.startsWith(`${school.waecCode}-`);

/** Fills in usernames on records being created. Used by the store for every insert. */
export function withIdentities<T>(key: string, items: T[], state: { users: User[]; students: Student[]; schools: School[] }): T[] {
  if (key === "users") {
    const users = items as unknown as User[];
    const fresh = nextPlatformUsernames([...state.users, ...users], users.filter((u) => !u.username).length);
    let i = 0;
    return users.map((u) => (u.username ? u : { ...u, username: fresh[i++]! })) as unknown as T[];
  }
  if (key === "students") {
    const students = items as unknown as Student[];
    const seqBySchool = new Map<string, number>();
    return students.map((st) => {
      const school = state.schools.find((s) => s.id === st.schoolId);
      if (st.schoolUsername || !needsSchoolUsername(st, school)) return st;
      const waec = school!.waecCode;
      const next = (seqBySchool.get(waec) ?? maxSeq([...state.students, ...students], waec)) + 1;
      seqBySchool.set(waec, next);
      return { ...st, schoolUsername: schoolUsername(waec, next) };
    }) as unknown as T[];
  }
  return items;
}

/** Issues WAEC-prefixed usernames to every student of a school that needs one. */
export function assignSchoolUsernames(students: Student[], school: School): { students: Student[]; issued: number } {
  if (!isValidWaec(school.waecCode)) return { students, issued: 0 };
  let seq = maxSeq(students, school.waecCode);
  const ordered = students.filter((s) => s.schoolId === school.id && needsSchoolUsername(s, school)).sort((a, b) => a.createdAt.localeCompare(b.createdAt) || a.studentNumber.localeCompare(b.studentNumber));
  const names = new Map(ordered.map((s) => [s.id, schoolUsername(school.waecCode, ++seq)]));
  return { students: students.map((s) => (names.has(s.id) ? { ...s, schoolUsername: names.get(s.id) } : s)), issued: names.size };
}

export type SignInMatch = { ok: true; userIds: string[]; via: "email" | "platform" | "school" | "staff" | "school_code" } | { ok: false; error: string };

export const SCHOOL_ADMIN_ROLE = "role_school_admin";

/** The codes a school administrator signs in with: the school's WAEC code and GES EMIS code (spec §10.1). */
export const schoolSignInCodes = (school: Pick<School, "waecCode" | "emisCode"> | undefined) => [school?.waecCode, school?.emisCode].map((c) => c?.trim() ?? "").filter(Boolean);

/**
 * School administrators of a real school sign in only with the school's WAEC
 * or GES EMIS code — no email or generated number. Until the school has either
 * code (e.g. just bulk-imported), they use their email so they can sign in and
 * complete the profile. The platform-run Vacation workspace has no codes.
 */
export function signsInWithSchoolCode(user: Pick<User, "roleId" | "schoolId">, schools: School[]) {
  if (user.roleId !== SCHOOL_ADMIN_ROLE || !user.schoolId) return false;
  const school = schools.find((x) => x.id === user.schoolId);
  return !!school && school.kind !== "vacation" && schoolSignInCodes(school).length > 0;
}

/**
 * Resolves what someone typed on the sign-in page (case-insensitive):
 * - school administrators: the school's WAEC code or GES EMIS code;
 * - students: school username, platform username or email;
 * - teachers: staff ID, email or platform username;
 * - everyone else: email or platform username.
 * A school code can match several administrators of the same school; the
 * password then decides which account signs in.
 */
export function resolveSignIn(identifier: string, state: { users: User[]; students: Student[]; teachers: Teacher[]; schools: School[] }): SignInMatch {
  const id = identifier.trim().toLowerCase();
  if (!id) return { ok: false, error: "Enter your email, username, staff ID or school code." };

  const bySchoolCode = state.schools.filter((x) => x.kind !== "vacation" && schoolSignInCodes(x).some((c) => c.toLowerCase() === id));
  if (bySchoolCode.length) {
    const admins = state.users.filter((u) => u.roleId === SCHOOL_ADMIN_ROLE && bySchoolCode.some((x) => x.id === u.schoolId));
    if (admins.length) return { ok: true, userIds: admins.map((u) => u.id), via: "school_code" };
  }

  const adminGuard = (u: User): SignInMatch | null =>
    signsInWithSchoolCode(u, state.schools) ? { ok: false, error: "School administrators sign in with the school's WAEC code or GES EMIS code." } : null;

  const byEmail = state.users.find((u) => u.email.toLowerCase() === id);
  if (byEmail) return adminGuard(byEmail) ?? { ok: true, userIds: [byEmail.id], via: "email" };
  const byPlatform = state.users.find((u) => u.username?.toLowerCase() === id);
  if (byPlatform) return adminGuard(byPlatform) ?? { ok: true, userIds: [byPlatform.id], via: "platform" };
  const student = state.students.find((x) => x.schoolUsername?.toLowerCase() === id);
  if (student) return { ok: true, userIds: [student.userId], via: "school" };
  // Staff IDs are issued by each school, so the same ID can exist at two schools.
  const staff = [...new Set(state.teachers.filter((t) => t.staffNumber.toLowerCase() === id).map((t) => t.userId))];
  if (staff.length === 1) return { ok: true, userIds: staff, via: "staff" };
  if (staff.length > 1) return { ok: false, error: "That staff ID is used at more than one school. Sign in with your email or platform username instead." };
  return { ok: false, error: "No account found for that email, username, staff ID or school code." };
}
