"use client";

import { Controller, useForm, useWatch } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { AppSelect } from "@/components/common/app-select";
import { Field } from "@/components/forms/field";
import type { SchoolClass, Student, Teacher } from "@/lib/types";
import { admissionYearProblem, indexNumberOf } from "@/lib/students";
import { cn } from "@/lib/utils";

const phone = z.string().trim().regex(/^\+?[\d\s]{9,16}$/, "Enter a valid phone number");

// ------------------------------------------------------------------ StudentForm (spec §57)

const studentSchema = z.object({
  firstName: z.string().trim().min(1, "Required"),
  lastName: z.string().trim().min(1, "Required"),
  gender: z.enum(["M", "F"]),
  dateOfBirth: z.string().min(1, "Required"),
  admissionYear: z.string().superRefine((v, ctx) => {
    const problem = admissionYearProblem(v);
    if (problem) ctx.addIssue({ code: "custom", message: problem });
  }),
  jhsIndexNumber: z.string().regex(/^\d{10}$/, "Enter the 10-digit JHS index number"),
  guardianName: z.string().trim().min(2, "Required"),
  guardianPhone: phone,
  email: z.union([z.literal(""), z.string().trim().email("Enter a valid email")]),
  classId: z.string(),
});
type StudentFields = z.infer<typeof studentSchema>;
export type StudentValues = Omit<StudentFields, "admissionYear"> & { admissionYear: number; indexNumber: string };

/**
 * Add / edit a student. The Student ID is generated by the platform (shown
 * read-only); the 12-digit index number is the JHS index plus the admission
 * year and must be unique across the platform.
 */
export function StudentForm({
  initial,
  classes,
  takenIndexes,
  previewNumber,
  onSubmit,
  onCancel,
  showClass = true,
}: {
  initial?: Partial<Student> & { classId?: string; email?: string };
  classes: SchoolClass[];
  /** 12-digit index numbers already registered, mapped to who holds them. */
  takenIndexes: Map<string, string>;
  /** The Student ID a new student would get for an admission year. */
  previewNumber?: (admissionYear: number) => string;
  onSubmit: (v: StudentValues) => void;
  onCancel: () => void;
  showClass?: boolean;
}) {
  const form = useForm<StudentFields>({
    resolver: zodResolver(
      studentSchema.superRefine((v, ctx) => {
        const holder = !admissionYearProblem(v.admissionYear) && /^\d{10}$/.test(v.jhsIndexNumber) ? takenIndexes.get(indexNumberOf(v.jhsIndexNumber, v.admissionYear)) : undefined;
        if (holder) ctx.addIssue({ code: "custom", message: `Already registered to ${holder}`, path: ["jhsIndexNumber"] });
      }),
    ),
    defaultValues: {
      firstName: initial?.firstName ?? "",
      lastName: initial?.lastName ?? "",
      gender: initial?.gender ?? "F",
      dateOfBirth: initial?.dateOfBirth ?? "",
      admissionYear: String(initial?.admissionYear ?? new Date().getFullYear()),
      jhsIndexNumber: initial?.jhsIndexNumber ?? "",
      guardianName: initial?.guardianName ?? "",
      guardianPhone: initial?.guardianPhone ?? "",
      email: initial?.email ?? "",
      classId: initial?.classId ?? "",
    },
  });
  const e = form.formState.errors;
  const [year, jhs] = useWatch({ control: form.control, name: ["admissionYear", "jhsIndexNumber"] });
  const yearOk = !admissionYearProblem(year);
  const studentId = initial?.studentNumber ?? (yearOk && previewNumber ? previewNumber(Number(year)) : "Generated when you save");
  const fullIndex = yearOk && /^\d{10}$/.test(jhs) ? indexNumberOf(jhs, year) : "";
  const heading = "text-xs font-semibold tracking-wide text-muted-foreground uppercase sm:col-span-2";

  return (
    <form
      onSubmit={form.handleSubmit((v) => onSubmit({ ...v, admissionYear: Number(v.admissionYear), indexNumber: indexNumberOf(v.jhsIndexNumber, v.admissionYear) }))}
      className="grid grid-cols-1 gap-4 sm:grid-cols-2"
      noValidate
    >
      <p className={heading}>Student</p>
      <Field label="First name" htmlFor="sf" error={e.firstName?.message} required>
        <Input id="sf" autoComplete="off" {...form.register("firstName")} />
      </Field>
      <Field label="Last name" htmlFor="sl" error={e.lastName?.message} required>
        <Input id="sl" autoComplete="off" {...form.register("lastName")} />
      </Field>
      <Field label="Gender" required>
        <Controller control={form.control} name="gender" render={({ field }) => <AppSelect value={field.value} onChange={field.onChange} options={[{ value: "F", label: "Female" }, { value: "M", label: "Male" }]} />} />
      </Field>
      <Field label="Date of birth" htmlFor="sdob" error={e.dateOfBirth?.message} required>
        <Input id="sdob" type="date" {...form.register("dateOfBirth")} />
      </Field>

      <p className={cn(heading, "mt-2 border-t pt-4")}>Admission &amp; identification</p>
      <Field label="Admission year" htmlFor="say" error={e.admissionYear?.message} required>
        <Input id="say" numeric="integer" maxLength={4} placeholder="e.g. 2026" {...form.register("admissionYear")} />
      </Field>
      <Field label="JHS index number" htmlFor="sjhs" error={e.jhsIndexNumber?.message} hint="10 digits, from the BECE results" required>
        <Input id="sjhs" numeric="integer" maxLength={10} placeholder="0012345678" className="font-mono tracking-wider" {...form.register("jhsIndexNumber")} />
      </Field>
      <Field label="Index number" htmlFor="sidx" hint="JHS index + admission year (12 digits). Used to find and match this student.">
        <Input id="sidx" readOnly tabIndex={-1} value={fullIndex} placeholder="Fills in automatically" className="font-mono tracking-wider" />
      </Field>
      <Field label="Student ID" htmlFor="sid" hint={initial?.studentNumber ? "Assigned by the platform — can't be changed" : "Assigned automatically when you save"}>
        <Input id="sid" readOnly tabIndex={-1} value={studentId} className="font-mono" />
      </Field>

      <p className={cn(heading, "mt-2 border-t pt-4")}>Contact</p>
      <Field label="Email" htmlFor="se" error={e.email?.message} hint="Optional — generated if empty" className="sm:col-span-2">
        <Input id="se" type="email" autoComplete="off" {...form.register("email")} />
      </Field>
      <Field label="Guardian name" htmlFor="sg" error={e.guardianName?.message} required>
        <Input id="sg" {...form.register("guardianName")} />
      </Field>
      <Field label="Guardian phone" htmlFor="sgp" error={e.guardianPhone?.message} required>
        <Input id="sgp" type="tel" placeholder="024 000 0000" {...form.register("guardianPhone")} />
      </Field>
      {showClass && (
        <Field label="Class" className="sm:col-span-2" hint="Also registers the student for the class's subjects">
          <Controller control={form.control} name="classId" render={({ field }) => <AppSelect value={field.value || "__none"} onChange={(v) => field.onChange(v === "__none" ? "" : v)} options={[{ value: "__none", label: "Assign later" }, ...classes.map((c) => ({ value: c.id, label: c.name }))]} />} />
        </Field>
      )}
      <div className="sticky -bottom-4 -mx-4 flex flex-col-reverse gap-2 border-t bg-popover px-4 py-3 sm:col-span-2 sm:static sm:mx-0 sm:flex-row sm:justify-end sm:border-0 sm:bg-transparent sm:p-0">
        <Button type="button" variant="outline" onClick={onCancel}>
          Cancel
        </Button>
        <Button type="submit">Save student</Button>
      </div>
    </form>
  );
}

// ------------------------------------------------------------------ TeacherForm (spec §57)

const teacherSchema = z.object({
  title: z.enum(["Mr.", "Mrs.", "Ms.", "Dr.", "Rev."]),
  firstName: z.string().trim().min(1, "Required"),
  lastName: z.string().trim().min(1, "Required"),
  gender: z.enum(["M", "F"]),
  staffNumber: z.string().trim().min(2, "Required"),
  specialization: z.string().trim().min(2, "e.g. ICT, Mathematics"),
  phone,
  email: z.string().trim().email("Enter a valid email"),
  status: z.enum(["active", "on_leave", "inactive"]),
});
export type TeacherValues = z.infer<typeof teacherSchema>;

export function TeacherForm({ initial, takenEmails, onSubmit, onCancel, suggestedNumber }: { initial?: Partial<Teacher> & { email?: string }; takenEmails: string[]; onSubmit: (v: TeacherValues) => void; onCancel: () => void; suggestedNumber?: string }) {
  const form = useForm<TeacherValues>({
    resolver: zodResolver(teacherSchema.refine((v) => !takenEmails.includes(v.email.toLowerCase()), { message: "A user with this email already exists", path: ["email"] })),
    defaultValues: {
      title: initial?.title ?? "Mr.",
      firstName: initial?.firstName ?? "",
      lastName: initial?.lastName ?? "",
      gender: initial?.gender ?? "M",
      staffNumber: initial?.staffNumber ?? suggestedNumber ?? "",
      specialization: initial?.specialization ?? "",
      phone: initial?.phone ?? "",
      email: initial?.email ?? "",
      status: initial?.status ?? "active",
    },
  });
  const e = form.formState.errors;
  return (
    <form onSubmit={form.handleSubmit(onSubmit)} className="grid gap-4 sm:grid-cols-6" noValidate>
      <Field label="Title" className="sm:col-span-2">
        <Controller control={form.control} name="title" render={({ field }) => <AppSelect value={field.value} onChange={field.onChange} options={["Mr.", "Mrs.", "Ms.", "Dr.", "Rev."].map((t) => ({ value: t, label: t }))} />} />
      </Field>
      <Field label="First name" htmlFor="tf" error={e.firstName?.message} required className="sm:col-span-2">
        <Input id="tf" {...form.register("firstName")} />
      </Field>
      <Field label="Last name" htmlFor="tl" error={e.lastName?.message} required className="sm:col-span-2">
        <Input id="tl" {...form.register("lastName")} />
      </Field>
      <Field label="Gender" className="sm:col-span-2">
        <Controller control={form.control} name="gender" render={({ field }) => <AppSelect value={field.value} onChange={field.onChange} options={[{ value: "M", label: "Male" }, { value: "F", label: "Female" }]} />} />
      </Field>
      <Field label="Staff ID" htmlFor="ts" error={e.staffNumber?.message} required className="sm:col-span-2">
        <Input id="ts" {...form.register("staffNumber")} />
      </Field>
      <Field label="Status" className="sm:col-span-2">
        <Controller control={form.control} name="status" render={({ field }) => <AppSelect value={field.value} onChange={field.onChange} options={[{ value: "active", label: "Active" }, { value: "on_leave", label: "On leave" }, { value: "inactive", label: "Inactive" }]} />} />
      </Field>
      <Field label="Specialisation" htmlFor="tsp" error={e.specialization?.message} required className="sm:col-span-6">
        <Input id="tsp" placeholder="e.g. ICT, Mathematics" {...form.register("specialization")} />
      </Field>
      <Field label="Email" htmlFor="te" error={e.email?.message} required className="sm:col-span-3">
        <Input id="te" type="email" {...form.register("email")} />
      </Field>
      <Field label="Phone" htmlFor="tp" error={e.phone?.message} required className="sm:col-span-3">
        <Input id="tp" type="tel" {...form.register("phone")} />
      </Field>
      <div className="flex justify-end gap-2 sm:col-span-6">
        <Button type="button" variant="outline" onClick={onCancel}>
          Cancel
        </Button>
        <Button type="submit">Save teacher</Button>
      </div>
    </form>
  );
}
